version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:23.0.1

    working_directory: ~/repo

    environment:
      SBT_OPTS: -Xmx6000m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-

      - run: cat /dev/null | sbt "set Test / parallelExecution := false" Test/compile

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}

      - run: cat /dev/null | sbt "set Test / parallelExecution := false" test
