steps:
  - checkout

  - restore_cache:
      keys:
        - v1-dependencies-{{ checksum "build.sbt" }}
        - v1-dependencies-

  - run: cat /dev/null | sbt "set Test / parallelExecution := false" Test/compile

  - save_cache:
      paths:
        - ~/.m2
      key: v1-dependencies--{{ checksum "build.sbt" }}

  - run: cat /dev/null | sbt "set Test / parallelExecution := false" test
